name: PHP Composer Build Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

#    - name: Run tests
#      run: composer test

    - name: Build application
      run: php awk-helper app:build awk-helper

#    - name: Verify build
#      run: |
#        chmod +x build/awk-helper
#        ./build/awk-helper --version

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: awk-helper-binary
        path: build/awk-helper
        retention-days: 90
